jms_security_extra:
    secure_all_services: false
    expressions: true

security:
    providers:
        fos_userbundle:
            id: fos_user.user_manager

    encoders:
        "FOS\UserBundle\Model\UserInterface": plaintext

    role_hierarchy:
     
        ROLE_TEACHER:     ROLE_STUDENT
        ROLE_SUPER_ADMIN: [ ROLE_ADMIN, ROLE_TEACHER, ROLE_ALLOWED_TO_SWITCH]

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false
  
             
        # Firewall teacher
        main:
            pattern: ^/                             # ^/ = tout ce qui commence par / = tout notre site
            form_login:                             # On définit notre méthode d'authentification
                provider:       fos_userbundle      # On lit l'authentification au provider définit plus haut 
                remember_me:    true                # On active la possibilité du "Se souvenir de moi" (désactivé par défaut)
                default_target_path: /
                login_path:          /
                check_path:          /login_check
            logout:  
                target: /index
            remember_me:
                key:         %secret%        # On définit la clé pour le remember_me (%secret% est un parametre de parameters.ini)
            anonymous:       true            # On autorise les utilisateurs anonymes (non identifiés)
            logout:          true            # On autorise la déconnexion manuelle (désactivé par défaut) 
            

    access_control: 
        #- { path: ^/teacher/, role: ROLE_TEACHER }
        #
        # You must uncomment the two following rules to restrict access to paths
        # starting with the /_internal prefix to only localhost
        #- { path: ^/_internal/secure, roles: IS_AUTHENTICATED_ANONYMOUSLY, ip: 127.0.0.1 }
        #- { path: ^/_internal/secure, roles: ROLE_NO_ACCESS }



    
