<?php

namespace FloBen\AnatomEasyBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * Level
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Level extends EntityRepository
{
}
