FloBen\AnatomEasyBundle\Entity\Exercice:
    type: entity
    table: Exercice
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
        title:
            type: string
            length: 45
            fixed: false
            nullable: true
            column: Title
        subject:
            type: string
            length: 45
            fixed: false
            nullable: true
            column: Subject
    manyToOne:
        level:
            targetEntity: Level
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                Level_id:
                    referencedColumnName: id
            orphanRemoval: false
        subjectsSubjectscol:
            targetEntity: Subjects
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                Subjects_Subjectscol:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
