FloBen\AnatomEasyBundle\Entity\Group:
    type: entity
    table: Group
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
        name:
            type: string
            length: 45
            fixed: false
            nullable: true
    manyToOne:
        level:
            targetEntity: Level
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                Level_id:
                    referencedColumnName: id
            orphanRemoval: false
        teacher:
            targetEntity: Teacher
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                Teacher_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
