FloBen\AnatomEasyBundle\Entity\HomeworkHasExercice:
    type: entity
    table: Homework_has_Exercice
    fields:
        done:
            type: boolean
            nullable: true
    oneToOne:
        homework:
            targetEntity: Homework
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                Homework_id:
                    referencedColumnName: id
            orphanRemoval: false
        exercice:
            targetEntity: Exercice
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                Exercice_id:
                    referencedColumnName: id
            orphanRemoval: false
    manyToOne:
        result:
            targetEntity: Result
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                Result_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
