FloBen\AnatomEasyBundle\Entity\Homework:
    type: entity
    table: Homework
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
        deadline:
            type: date
            nullable: true
    manyToOne:
        student:
            targetEntity: Student
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                Student_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
