FloBen\AnatomEasyBundle\Entity\Sandbox:
    type: entity
    table: Sandbox
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
        date:
            type: datetime
            nullable: false
    manyToOne:
        exercice:
            targetEntity: Exercice
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                Exercice_id:
                    referencedColumnName: id
            orphanRemoval: false
        result:
            targetEntity: Result
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                Result_id:
                    referencedColumnName: id
            orphanRemoval: false
        student:
            targetEntity: Student
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                Student_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
