FloBen\AnatomEasyBundle\Entity\Subjects:
    type: entity
    table: Subjects
    fields:
        id:
            id: true
            type: string
            length: 45
            fixed: false
            nullable: false
            generator:
                strategy: IDENTITY
    lifecycleCallbacks: {  }
